#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: connect-vpn
# ARCHIVO: prerm
# DESCRIPCIÓN: Prepara el sistema para que el paquete sea removido.
# COPYRIGHT:
#  (C) 2016 Victor Pino <victopin0@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

case ${1} in

    remove|upgrade|deconfigure)
	
	UHOME="/home"
	USERS=$(cut -d':' -f 1 /etc/passwd)

	for u in $USERS; do
	    
	    ID=$(id -u $u)
	    
	    if [ $ID -ge 1000 ] ; then
				
			if [ -d ${UHOME}/${u} ] ; then
				
				rm -f ${UHOME}/${u}/Escritorio/connect-vpn.desktop
		    
		    fi
	    fi

	done 
    
    ;;

    failed-upgrade)

    ;;

    *)

        echo "prerm no reconoce el argumento '"${1}"'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0
